swagger: "2.0"
info:
  title: Duolingo Unofficial API (Main)
  description: Unofficial API description for Duolingo.
  version: 1.1.1
host: www.duolingo.com
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header

security:
  - BearerAuth: []

paths:
  /goals/schema:
    $ref: "./operations/goals.yaml"

  /leaderboards/{leaderboardID}/users/{userID}:
    $ref: "./operations/leaderboards.yaml"

  /users/{userID}/achievements:
    $ref: "./operations/achievements.yaml"

  /login:
    $ref: "./operations/login.yaml"

  /shop-items:
    $ref: "./operations/shop_items.yaml"

  /users/{userID}:
    $ref: "./operations/users_logged.yaml"

  /2017-06-30/users:
    $ref: "./operations/users_not_logged.yaml"

  /2017-06-30/users/{userID}/subscriptions:
    $ref: "./operations/subscriptions.yaml"

  /2017-06-30/users/{userID}/xp_summaries:
    $ref: "./operations/xpsummaries.yaml"

  /2017-06-30/shop-items:
    $ref: "./operations/shop_items.yaml"

  /notifications:
    $ref: "./operations/notifications.yaml"
